export default {
  products: [
    {
      id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
    {
      id: "3",
      name: "Chino Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
    {
      id: "4",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
    {
      name: "Chino Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
    {
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
    {
      name: "Chino Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },
  ],
};
